services:
  postgres:
    image: postgres:16
    container_name: gestao_colaboradores_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gestao_colaboradores
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gestao_colaboradores"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - gestao_colaboradores_data:/var/lib/postgresql/data

volumes:
  gestao_colaboradores_data:
